[project]
name = "function-call-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "groq>=0.25.0",
    "python-dotenv>=1.1.0",
    "streamlit>=1.45.1",
]
